markdown: kramdown
permalink: /:title/
url: https://venyao.github.io/
name: venyao
author: venyao
qq: 1481758069
email: venyao@qq.com 
github: venyao
highlighter: rouge
safe: true
paginate: 20
about: "Personal blog of venyao"
